### ISSUE TITLE
Merge both pt-BR translations into one

### ISSUE THREAD

**Issue by ghost** [TecArt/TecArt-Ticket-System#19]
There's currently two Brazilian Portuguese translations [here](https://github.com/TecArt/TecArt-Ticket-System/blob/master/lang/pt-BR.php) and [here](https://github.com/TecArt/TecArt-Ticket-System/blob/master/lang/pt-br.php), these should be merged into one.

**Comment by moraesslucas** [comment]
#21 Pull Request addresses this issue
