### ISSUE TITLE
Update jQuery to current version

### ISSUE THREAD

**Issue by ghost** [TecArt/TecArt-Ticket-System#3]
The jQuery version in this release is too old and needs to be updated. This also means updating/testing the client side code in the header and `javascripts.js`: https://github.com/TecArt/TecArt-Ticket-System/blob/dd6df92b9db2c095e887f5de088a5ab4eb150036/application/views/common/header.php#L9-L10

**Comment by cenoura** [comment]
I'll take this one too.
